<a href="https://colab.research.google.com/github/phucph/OCR/blob/master/Copy_of_PixelLink_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Scene Text Detection with PixelLink

This notebook uses [PixelLink](https://github.com/ZJULearning/pixel_link) to detect text areas on a given image.

For other deep-learning Colab notebooks, visit [tugstugi/dl-colab-notebooks](https://github.com/tugstugi/dl-colab-notebooks).


## Install PixelLink

In [ ]:
import os
from os.path import exists, join, basename, splitext, abspath
from getpass import getpass
password = getpass('BitBucket password')
os.environ['BITBUCKET_AUTH'] = 'phucph98' + ':' + password

# !git clone https://$BITBUCKET_AUTH@bitbucket.org/{user}/repository.git
git_repo_url = 'https://$BITBUCKET_AUTH@bitbucket.org/gemcorp/ocr.git'
project_name = splitext(basename(git_repo_url))[0]
if not exists(project_name):
  # clone and install
  !git clone -q $git_repo_url
  # # make opencv3 compatible
  # os.environ['PYTHONPATH'] += ':' + join(abspath(project_name), 'pylib/src')
  #!cd $project_name && pip install -q -r requirements.txt
  
import sys
sys.path.append(project_name)
# 

In [2]:
import os
from os.path import exists, join, basename, splitext, abspath
git_repo_url = 'https://github.com/phucph/OCR.git'
project_name = splitext(basename(git_repo_url))[0]
if not exists(project_name):
  # clone and install
  !git clone -q $git_repo_url
  

In [3]:
os.chdir('/content/OCR/')
# !git pull



In [4]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [5]:
import zipfile
from google.colab import drive

# drive.mount('/content/sample_data/')
zip_ref = zipfile.ZipFile("/content/drive/My Drive/ocr/data/test_images.zip", 'r')
zip_ref.extractall("/content/OCR/dataset/")
zip_ref = zipfile.ZipFile("/content/drive/My Drive/ocr/data/train_images.zip", 'r')
zip_ref.extractall("/content/OCR/dataset/")
zip_ref = zipfile.ZipFile("/content/drive/My Drive/ocr/data/train_gt.zip", 'r')
zip_ref.extractall("/content/OCR/dataset/")
zip_ref.close()

## Download pretrained model

## Detect scene text on a test image

First, dowload a test image from internet:

In [ ]:
print(project_name)


ocr


In [ ]:
!pwd

/content


In [ ]:
!pwd
import os
os.chdir('/content/ocr/text_detector/PixelLink')


/content


In [ ]:
import zipfile
from google.colab import drive

# drive.mount('/content/sample_data/')
zip_ref = zipfile.ZipFile("/content/drive/My Drive/ocr/data/test_images.zip", 'r')
zip_ref.extractall("/content/ocr/text_detector/PixelLink/dataset/")
zip_ref = zipfile.ZipFile("/content/drive/My Drive/ocr/data/train_images.zip", 'r')
zip_ref.extractall("/content/ocr/text_detector/PixelLink/dataset/")
zip_ref = zipfile.ZipFile("/content/drive/My Drive/ocr/data/train_gt.zip", 'r')
zip_ref.extractall("/content/ocr/text_detector/PixelLink/dataset/")
zip_ref.close()

In [ ]:
from google.colab import auth
auth.authenticate_user()

In [ ]:

# !gsutil cp -r /content/ocr/text_detector/PixelLink/dataset/test_images/ gs://pixel-link/data
# !gsutil cp -r /content/ocr/text_detector/PixelLink/dataset/train_images/ gs://pixel-link/data
# !gsutil cp -r /content/ocr/text_detector/PixelLink/dataset/train_gt/ gs://pixel-link/data

Run PixelLink on the above test image:

In [ ]:
!pwd
!ls
# !rm -rf checkpoints
# !ls


In [6]:
!pip uninstall --y torch torchvision
!pip install torch==1.5.1+cu101 torchvision==0.6.1+cu101 -f https://download.pytorch.org/whl/torch_stable.html

Uninstalling torch-1.8.1+cu101:
  Successfully uninstalled torch-1.8.1+cu101
Uninstalling torchvision-0.9.1+cu101:
  Successfully uninstalled torchvision-0.9.1+cu101
Looking in links: https://download.pytorch.org/whl/torch_stable.html
     |████████████████████████████████| 704.4MB 23kB/s 
     |████████████████████████████████| 6.7MB 57.9MB/s 
ERROR: torchtext 0.9.1 has requirement torch==1.8.1, but you'll have torch 1.5.1+cu101 which is incompatible.


In [7]:
# !pip install torch torchvision
# !pip install torch
!pip install opencv-python==3.4.2.17
!pip install Polygon3
!pip install pyclipper
!pip install scipy==1.1.0


     |████████████████████████████████| 25.0MB 113kB/s 
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.
  Found existing installation: opencv-python 4.1.2.30
    Uninstalling opencv-python-4.1.2.30:
      Successfully uninstalled opencv-python-4.1.2.30
  Created wheel for Polygon3: filename=Polygon3-3.0.9.1-cp37-cp37m-linux_x86_64.whl size=102603 sha256=9b4de6c4898a361b31fda04a1ca8d32bd43153966f3ca5c1db7965fed101306a
  Stored in directory: /root/.cache/pip/wheels/d8/20/1d/52982f2c8dd3794845145b221fe006028e16aa5d80646136ff
Successfully built Polygon3
     |████████████████████████████████| 133kB 7.5MB/s 
     |████████████████████████████████| 31.2MB 175kB/s 
ERROR: pymc3 3.11.2 has requirement scipy>=1.2.0, but you'll have scipy 1.1.0 which is incompatible.
ERROR: plotnine 0.6.0 has requirement scipy>=1.2.0, but you'll have scipy 1.1.0 which is incompatible.
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,

In [8]:
! nvidia-smi

Thu May 20 09:27:34 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.19.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P0    26W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
# !pip uninstall --y torch torchvision
# !pip install torch torchvision

Uninstalling torch-1.5.1+cu101:
  Successfully uninstalled torch-1.5.1+cu101
Uninstalling torchvision-0.6.1+cu101:
  Successfully uninstalled torchvision-0.6.1+cu101
     |████████████████████████████████| 804.1MB 19kB/s 
     |████████████████████████████████| 17.4MB 37.6MB/s 


In [ ]:
!nvcc --version
import torch
print(torch.__version__)

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Wed_Jul_22_19:09:09_PDT_2020
Cuda compilation tools, release 11.0, V11.0.221
Build cuda_11.0_bu.TC445_37.28845127_0
1.5.1+cu101


In [ ]:
!rm -rf images
!mkdir images



In [ ]:
 !nvidia-smi

Tue May 11 05:24:18 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.19.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P0    27W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

Now, visualize the result:

In [ ]:
# !CUDA_VISIBLE_DEVICES=0 python train_ic15.py --arch vgg16 --batch_size 8 --checkpoint /content/drive/MyDrive/checkpoint/

In [19]:
   !CUDA_VISIBLE_DEVICES=0,1,2,3 python train_ic15.py --pretrain /content/drive/MyDrive/ocr/checkpoint/_pretrain_model640_size1280/_pretrain_s640/checkpoint_500.pth  --arch vgg16 --batch_size 2 --checkpoint /content/drive/MyDrive/ocr/checkpoint/_pretrain_model640_size1280/


checkpoint path: /content/drive/MyDrive/ocr/checkpoint/_pretrain_model640_size1280/_pretrain_s640
init lr: 0.00100000
('schedule: ', [503])
2021-05-20 11:05:28.778917: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Using pretrained model.

Epoch: [1 | 503] LR: 0.001000
/usr/local/lib/python3.7/dist-packages/torch/nn/_reduction.py:43: UserWarning: size_average and reduce args will be deprecated, please use reduction='none' instead.
  warnings.warn(warning.format(ret))
[1912 1913 1914 ... 3438 3439 3440] [1088 1089 1090 ... 4127 4128 4129]
(1/352) Batch: 4.731s | TOTAL: 0min | ETA: 28min | Loss: 0.5390| Loss_cls: 0.0723 | Acc_t:  0.9705 | IOU_t:  0.9296
[1604 1605 1606 ... 3083 3084 3085] [1770 1771 1772 ... 4441 4442 4443]
(21/352) Batch: 1.322s | TOTAL: 0min | ETA: 7min | Loss: 0.5406| Loss_cls: 0.0823 | Acc_t:  0.9472 | IOU_t:  0.9174
[1475 1476 1477 ... 3020 3021 3022] [1442 1443 1444 ... 4199 4200 4201]
(41/352) 

In [16]:
!CUDA_VISIBLE_DEVICES=0,1 python train_ic15.py --pretrain /content/drive/MyDrive/checkpoint/_pretrain_OHEM/checkpoint_250.pth --arch vgg16 --batch_size 2 --checkpoint /content/drive/MyDrive/_

checkpoint path: /content/drive/MyDrive/__pretrain_s640
init lr: 0.00100000
('schedule: ', [503])
2021-05-20 10:54:04.734656: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Using pretrained model.
Traceback (most recent call last):
  File "train_ic15.py", line 389, in <module>
    main(args)
  File "train_ic15.py", line 325, in main
    assert os.path.isfile(args.pretrain), 'Error: no checkpoint directory found!'
AssertionError: Error: no checkpoint directory found!


In [ ]:
!CUDA_VISIBLE_DEVICES=0 python test_ic15.py --resume /content/drive/MyDrive/ocr/checkpoint/_pretrain_2176x2176_20/model_test/checkpoint_70.pth

In [ ]:
%load_ext tensorboard

In [ ]:
!CUDA_VISIBLE_DEVICES=0 python test_ic15.py --resume /content/drive/MyDrive/ocr/checkpoint/_pretrain_model640_size1280/_pretrain_s640/checkpoint_500.pth

Loading model and optimizer from checkpoint '/content/drive/MyDrive/ocr/checkpoint/_pretrain_model640_size1280/_pretrain_s640/checkpoint_500.pth'
Loaded checkpoint '/content/drive/MyDrive/ocr/checkpoint/_pretrain_model640_size1280/_pretrain_s640/checkpoint_500.pth' (epoch 501)
progress: 0 / 360
fps: 0.24
0 / 360 X51006554841.jpg
progress: 1 / 360
fps: 0.12
1 / 360 X51005568866.jpg
progress: 2 / 360
fps: 0.11
2 / 360 X51005676534.jpg
progress: 3 / 360
fps: 0.11
3 / 360 X51006620175.jpg
progress: 4 / 360
fps: 0.12
4 / 360 X51006311714.jpg
progress: 5 / 360
fps: 0.13
5 / 360 X51005230621.jpg
progress: 6 / 360
fps: 0.12
6 / 360 X51006913060.jpg
progress: 7 / 360
fps: 0.13
7 / 360 X51006556810.jpg
progress: 8 / 360
fps: 0.12
8 / 360 X51005719823.jpg
progress: 9 / 360
fps: 0.11
9 / 360 X51007846372.jpg
progress: 10 / 360
fps: 0.12
10 / 360 X51006619782.jpg
progress: 11 / 360
fps: 0.11
11 / 360 X51006008090.jpg
progress: 12 / 360
fps: 0.12
12 / 360 X51006557507.jpg
progress: 13 / 360
fps: 0.1

In [ ]:
os.chdir('/content/OCR/eval/ic19/')
!python script.py -g=submit.zip -s=../../outputs/OHEM_c640.zip

Calculated!{"precision": 0.9474734042553191, "recall": 0.9661255299348563, "hmean": 0.9567085646112524}